entry_tracker/config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  resources :passages
  resources :cards do
    member do
      patch :grant_authorization
      patch :revoke_authorization
    end
  end

  namespace :api, defaults: {format: 'json'} do
    resources :cards, only: [:create]
    resources :passages, only: [:create]
  end

end

entry_tracker/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

entry_tracker/app/models/card.rb
# frozen_string_literal: true

class Card < ApplicationRecord
  self.primary_key = :uid
  has_many :passages, foreign_key: :card_uid, inverse_of: :card

  validates :uid, presence: true, uniqueness: true
  validates :authorized, inclusion: { in: [true, false] }

  def to_s
    uid
  end
end

entry_tracker/app/models/passage.rb
class Passage < ApplicationRecord
  belongs_to :card, foreign_key: :card_uid, inverse_of: :passages

  enum passage_type: { exit: 0, entry: 1 }

  validates :card, presence: true
  validates :passage_type, presence: true
  validates :authorized, presence: true, inclusion: { in: [true, false] }

end

entry_tracker/app/controllers/api/api_controller.rb
module Api
  class ApiController < ActionController::Base
    protect_from_forgery with: :null_session
    skip_before_action :verify_authenticity_token
  end
end

entry_tracker/app/controllers/api/cards_controller.rb
module Api
  class CardsController < ApiController

    def create
      card = Card.new(uid: params[:uid])

      if card.save

        render json: card, status: :ok
      else
        render json: { errors: card.errors.messages }, status: :unprocessable_entity
      end
    end

    private

    def card_params
      params.permit(:uid, :authorized)
    end
  end
end

entry_tracker/app/controllers/api/passages_controller.rb
module Api
  class PassagesController < ApiController

    def create
      passage = Passage.new(passage_params)

      passage.authorized = passage.card&.authorized?

      if passage.save
        render json: passage, status: :ok
      else
        render json: { errors: passage.errors.messages }, status: :unprocessable_entity
      end
    end

    private

    def passage_params
      params.permit(:passage_type, :card_uid)
    end
  end
end

entry_tracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

entry_tracker/app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy,
                                  :grant_authorization, :revoke_authorization]

  # GET /cards
  # GET /cards.json
  def index
    @search = Card.ransack(params[:q])
    @cards = @search.result(distinct: true).page(params[:page]).per(15)
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @passages = @card.passages
  end

  # GET /cards/new
  def new
    @card = Card.new
  end


  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def grant_authorization
    respond_to do |format|
      if @card.update(authorized: true)
        format.html { redirect_to cards_path, notice: 'Authorization granted successfully.' }
      else
        format.html { redirect_to cards_path, notice: 'Granting authorization failed!.' }
      end
    end
  end
  def revoke_authorization
    respond_to do |format|
      if @card.update(authorized: false)
        format.html { redirect_to cards_path, notice: 'Authorization revoked successfully.' }
      else
        format.html { redirect_to cards_path, notice: 'Revoking authorization failed!.' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:uid, :authorized)
    end
end

entry_tracker/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

entry_tracker/app/controllers/passages_controller.rb
class PassagesController < ApplicationController
  before_action :set_passage, only: [:show, :edit, :update, :destroy]

  # GET /passages
  # GET /passages.json
  def index
    @search = Passage.ransack(params[:q])
    @passages = @search.result(distinct: true).page(params[:page]).per(15)
  end

  # GET /passages/1
  # GET /passages/1.json
  def show
  end

  # GET /passages/new
  def new
    @passage = Passage.new
  end

  # GET /passages/1/edit
  def edit
  end

  # POST /passages
  # POST /passages.json
  def create
    @passage = Passage.new(passage_params)

    respond_to do |format|
      if @passage.save
        format.html { redirect_to @passage, notice: 'Passage was successfully created.' }
        format.json { render :show, status: :created, location: @passage }
      else
        format.html { render :new }
        format.json { render json: @passage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passages/1
  # PATCH/PUT /passages/1.json
  def update
    respond_to do |format|
      if @passage.update(passage_params)
        format.html { redirect_to @passage, notice: 'Passage was successfully updated.' }
        format.json { render :show, status: :ok, location: @passage }
      else
        format.html { render :edit }
        format.json { render json: @passage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passages/1
  # DELETE /passages/1.json
  def destroy
    @passage.destroy
    respond_to do |format|
      format.html { redirect_to passages_url, notice: 'Passage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passage
      @passage = Passage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def passage_params
      params.require(:passage).permit(:authorized, :passage_type, :card_id)
    end
end

entry_tracker/app/helpers/application_helper.rb
module ApplicationHelper
end

entry_tracker/app/helpers/cards_helper.rb
module CardsHelper
end

entry_tracker/app/helpers/passages_helper.rb
module PassagesHelper
end

entry_tracker/app/views/cards/_form.html.erb
<div class='row'>
  <div class='col-md-6'>
    <%= simple_form_for(@card) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs">
        <%= f.input :uid%>
        <%= f.label :authorized %>
        <br/>
        <%= f.collection_radio_buttons :authorized, [[true, 'Yes'], [false, 'No']], :first, :last %>
      </div>

      <div class="form-actions">
        <%= f.button :submit %>
      </div>
    <% end %>

  </div>
</div>

entry_tracker/app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card, class: 'btn btn-default' %> |
<%= link_to 'Back', cards_path, class: 'btn btn-info' %>

entry_tracker/app/views/cards/index.html.erb
<% if notice %>
  <p id="notice" class='alert alert-info'><%= notice %></p>
<% end %>

<h1>Cards</h1>


<%= search_form_for @search do |f| %>

  <%= f.label :uid %>
  <%= f.search_field :uid_cont %>

  <%= f.select :authorized_eq, options_for_select([
        ['authorized', true],
        ['unauthorized', false]
      ] , @search.authorized)  %>

  <%= f.submit %>

  <%= link_to 'Clear', cards_path, class: 'btn btn-default' %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sort_link(@search, :uid, "UID") %></th>
      <th><%= sort_link(@search, :authorized, "Authorized") %></th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.uid %></td>
        <td><%= card.authorized %></td>
        <% if card.authorized? %>
          <td><%= link_to 'Revoke Authorization', revoke_authorization_card_path(card),
              method: :patch, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        <% else %>
          <td><%= link_to 'Grant Authorization', grant_authorization_card_path(card),
              method: :patch, data: { confirm: 'Are you sure?' }, class: 'btn btn-success' %></td>
        <% end %>
        <td><%= link_to 'Show', card, class: 'btn btn-default' %></td>
        <td><%= link_to 'Edit', edit_card_path(card), class: 'btn btn-info' %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @cards %>
<br>

<%= link_to 'New Card', new_card_path, class: 'btn btn-info' %>

entry_tracker/app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

entry_tracker/app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Card UID: <%= @card.uid %></h3>
<h4>authorized: <%= @card.authorized %></h4>
<% if @card.authorized? %>
  <%= link_to 'Revoke Authorization', revoke_authorization_card_path(@card),
      method: :patch, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
<% else %>
  <%= link_to 'Grant Authorization', grant_authorization_card_path(@card),
      method: :patch, data: { confirm: 'Are you sure?' }, class: 'btn btn-success' %>
<% end %>

<br />
<h4>Passages:</h4>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Authorized</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @passages.each do |passage| %>
      <tr>
        <td><%= passage.created_at %></td>
        <td><%= passage.authorized %></td>
        <td><%= passage.passage_type %></td>

        <td><%= link_to 'Show', passage, class: 'btn btn-default' %></td>
        <td><%= link_to 'Edit', edit_passage_path(passage), class: 'btn btn-info' %></td>
        <td><%= link_to 'Destroy', passage, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

entry_tracker/app/views/home/index.html.erb
<%= link_to 'Cards', cards_path, class: 'btn btn-success' %>
<br>
<br>
<%= link_to 'Passages', passages_path, class: 'btn btn-primary' %>

entry_tracker/app/views/layouts/_header.html.erb
<div class="alert alert-info">
  <h1>
    <%= link_to '/' do %>
      Entry Tracker
      <i class="glyphicon glyphicon-eye-open"></i>
    <% end %>
  </h1>
</div>

entry_tracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EntryTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class='container'>

      <%= yield %>
    </div>
  </body>
</html>

entry_tracker/app/views/passages/_form.html.erb
<%= simple_form_for(@passage) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :authorized %>
    <%= f.collection_radio_buttons :passage_type, [[:entry, 'Entry'], [:exit, 'Exit']], :first, :last %>
    <%= f.association :card %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

entry_tracker/app/views/passages/edit.html.erb
<h1>Editing Passage</h1>

<%= render 'form', passage: @passage %>

<%= link_to 'Show', @passage, class: 'btn btn-default' %> |
<%= link_to 'Back', passages_path, class: 'btn btn-info' %>

entry_tracker/app/views/passages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Passages</h1>

<%= search_form_for @search do |f| %>

  <%= f.label :card_uid %>
  <%= f.search_field :card_uid_cont %>

  <%= f.select :authorized_eq, options_for_select([
        ['authorized', true],
        ['unauthorized', false]
      ] , @search.authorized)  %>

  <%= f.label :passage_type %>
  <%= f.select :passage_type_eq, options_for_select([
        ['entry', 1],
        ['exit', 0]
      ] , @search.passage_type)  %>

  <%= f.submit %>

  <%= link_to 'Clear', passages_path, class: 'btn btn-default' %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= sort_link(@search, :created_at, "Date") %></th>
      <th><%= sort_link(@search, :card_uid, "Card UID") %></th>
      <th><%= sort_link(@search, :authorized, "Authorized") %></th>
      <th><%= sort_link(@search, :passage_type, "Type") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @passages.each do |passage| %>
      <tr>
        <td><%= passage.created_at %></td>
        <td><%= passage.card.uid %></td>
        <td><%= passage.authorized %></td>
        <td><%= passage.passage_type %></td>

        <td><%= link_to 'Show', passage, class: 'btn btn-default' %></td>
        <td><%= link_to 'Edit', edit_passage_path(passage), class: 'btn btn-info' %></td>
        <td><%= link_to 'Destroy', passage, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Passage', new_passage_path, class: 'btn btn-info' %>

entry_tracker/app/views/passages/new.html.erb
<h1>New Passage</h1>

<%= render 'form', passage: @passage %>

<%= link_to 'Back', passages_path %>

entry_tracker/app/views/passages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Authorized:</strong>
  <%= @passage.authorized %>
</p>

<p>
  <strong>Type:</strong>
  <%= @passage.passage_type %>
</p>

<p>
  <strong>Card:</strong>
  <%= @passage.card %>
</p>

<%= link_to 'Edit', edit_passage_path(@passage) %> |
<%= link_to 'Back', passages_path %>